version: '3'
services:
  nginx:
    depends_on:
      - amigo
    image: real/nginx
    links:
      - amigo:amigo
    ports:
      - "80:80"
  amigo:
    image: real/amigo
    links:
      - db:db
    volumes:
      - ./amigo-datavolume:/amigo-datavolume
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: amigobase
    volumes:
      - amigo-datavolume:/var/lib/mysql
volumes:
  amigo-datavolume: